---
- name: Configure MongoDB Replica Set
  hosts: mongodb                        # Targets the [mongodb] hosts in the inventory.ini
  become: yes                           # Elevated privileges
  tasks:
    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB service
      service:
        name: mongod
        state: started

    - name: Configure MongoDB replica set
      command: |
        mongo --eval "rs.initiate({
          _id: 'aws_replicaset',
          members: [
            {% for host in groups['mongodb'] %}
            { _id: {{ loop.index0 }}, host: '{{ hostvars[host].ansible_ssh_host }}:27017' }{% if not loop.last %},{% endif %}
            {% endfor %}
          ]
        })"
      ignore_errors: yes

    - name: Create admin user (customize this for your security needs)
      command: |
        mongo admin --eval "db.createUser({user: 'admin', pwd: 'admin', roles: ['root']})"
      ignore_errors: yes
